# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classify',
            field=models.CharField(default=datetime.datetime(2016, 2, 7, 15, 51, 51, 364545, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
